<?php

/**
 * @file
 * Primary module hooks for Aqto AI Core module.
 */

/**
 * Implements hook_aqto_ai_actions_available().
 *
 * @return array
 */
function aqto_ai_core_aqto_ai_actions_available(): array
{
    return [
        'clear_caches' => [
            [
                'description' => 'Clear all caches.',
                'service_name' => 'aqto_ai_core.site_actions_manager',
                'method' => 'clearCaches',
                'args' => [],
            ],
        ],
        'enable_modules' => [
            [
                'description' => 'Enable one or more modules.',
                'service_name' => 'aqto_ai_core.site_actions_manager',
                'method' => 'enableModules',
                'args' => [
                    'module_names' =>
                    'A general description provided by user of the module(s) to enable.',

                ],
            ],
        ],
        'disable_modules' => [
            [
                'description' => 'Disable one or more modules.',
                'service_name' => 'aqto_ai_core.site_actions_manager',
                'method' => 'disableAndUninstallModules',
                'args' => [
                    'module_names' => 'A general description provided by user of the module(s) to enable.',
                ],
            ],
        ],
        'make_main_menu_links' => [
            [
                'description' => 'Make one or more menu links from provided menu name, and then menu_data array of title -> url data.',
                'service_name' => 'aqto_ai_core.site_actions_manager',
                'method' => 'makeMenuLinks',
                'args' => [
                    'menu_name' => 'The menu name',
                    'menu_data' => [
                        'title' => 'url',
                    ],
                ],
            ],
        ],
        'update_site_name' => [
            [
                'description' => 'Update the site name.',
                'service_name' => 'aqto_ai_core.site_actions_manager',
                'method' => 'updateSiteName',
                'args' => [
                    'site_name' => 'The new site name',
                ],
            ],
        ],
        'create_new_random_article' => [
            'description' => 'Create a new article with a fun title and body about a random topic from health, science, or math.',
            'service_name' => 'aqto_ai_core.site_actions_manager',
            'method' => 'createMultipleArticles',
            'args' => [
                'numberToCreate' => 'always 1 in this case',
            ]
        ],
        'create_multiple_new_random_articles' => [
            'description' => 'Create multiple articles with fun titles and bodies about random topics from health, science, or math.',
            'service_name' => 'aqto_ai_core.site_actions_manager',
            'method' => 'createMultipleArticles',
            'args' => [
                'numberToCreate' => 'A number that can be a max of 20.',
            ]
        ],
        'get_enabled_modules_report' => [
            'description' => 'Get a report of all enabled modules.',
            'service_name' => 'aqto_ai_core.site_actions_manager',
            'method' => 'generateEnabledModulesReport',
            'args' => [],
        ],
        'get_available_actions_with_descriptions' => [
            'description' => 'Get a list of all available actions with descriptions.',
            'service_name' => 'aqto_ai_core.site_actions_manager',
            'method' => 'get_available_actions_with_descriptions',
            'args' => [],
        ],

    ];
}
